name: AMSSync
version: '${version}'
main: io.github.darinc.amssync.AMSSyncPlugin
api-version: '1.21'
author: darinc
description: Discord-MCMMO integration for Amazing Minecraft Server
website: https://github.com/darinc/ams-sync

depend:
  - mcMMO

softdepend: []

load: POSTWORLD

commands:
  amssync:
    description: Manage Discord-Minecraft user linking
    usage: /amssync <add|remove|list|players|quick|metrics>
    permission: amssync.admin

permissions:
  amssync.admin:
    description: Administrator permissions for AMSSync
    default: op
  amssync.link:
    description: Allows players to link their Discord account
    default: true
